name = "initflow"
compatibility_date = "2025-05-26"
compatibility_flags = ["nodejs_compat"]
node_compat = true

[site]
bucket = "./build/client"

[build]
command = "pnpm run build"

[build.upload]
format = "modules"
main = "build/server/index.js"

# Enable node.js compatibility
[build.environment]
NODE_VERSION = "18"

# Polyfill node built-ins
[[unsafe.bindings]]
name = "nodejs_compat"
type = "nodejs_compat"
