# wrangler.toml
name             = "initflow"            # your site’s name
project_name     = "initflow"            # must match your Pages project
compatibility_date  = "2025-05-26"       # today’s date

# polyfill Node built-ins for your Functions
compatibility_flags = ["nodejs_compat"]

[build]
# your build script
command   = "pnpm run build"
# where your client bundle lives
directory = "build/client"

# point Pages at your Functions (SSR handlers)
functions = "build/server"
