#:schema node_modules/wrangler/config-schema.json
name = "initflow"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"
pages_build_output_dir = "./build/client"
send_metrics = false

# Add node compatibility for built-in modules
[build]
command = "pnpm run build"

# Ensure proper node compatibility
node_compat = true