#:schema node_modules/wrangler/config-schema.json
name = "initflow"
project_name = "initflow"  # Add this if your Cloudflare Pages project is also called "initflow"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
send_metrics = false

# 👇 Path to your static frontend output (like index.html, JS/CSS, etc.)
pages_build_output_dir = "./build/client"

# 👇 Path to your SSR function (where build/server/index.js lives)
pages_functions_dir = "./build/server"
